### ISSUE TITLE
OrenJS → Orenburg Developers Meetup

### ISSUE THREAD

**Issue by igoradamenko** [web-standards-ru/cityjs-list#19]
Там оренбургская тусовка переименовалась: https://vk.com/wall-99379110_146

Не решил, стоит ли переименовать и прислать ПР, или же нужно вообще их убрать, ибо теперь это не только фронтенд-конференция. Поэтому просто ишью.

**Comment by vslinko** [comment]
имхо, убрать

**Comment by pepelsbey** [comment]
Давайте убирать, тоже ПР можно
